<?php
/**
 * Created by Andrey Stepanenko.
 * User: webnitros
 * Date: 14.09.2023
 * Time: 11:57
 */


class Style extends \Symfony\Component\Console\Style\SymfonyStyle
{
    public function block($messages, string $type = null, string $style = null, string $prefix = ' ', bool $padding = false, bool $escape = true)
    {
        $escape = true;
        $prefix = '';
        $padding = false;
        parent::block($messages, $type, $style, $prefix, $padding, $escape); // TODO: Change the autogenerated stub
    }
}
